import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import axios from 'axios'
import { use, useState } from 'react'
import InputBox from '@/components/searchBox'
import WeatherInfo from '@/components/weatherInfo'
import ErrorInfo from '@/components/errorInfo'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [errorMessage, setErrorMessage] = useState('');
  const [data, setData] = useState({});
  const [location, setLocation] = useState('');
  const [weather, setWeather] = useState('');
  const [temp, setTemp] = useState('');
  const [feelsLikeTemp, setFeelsLikeTemp] = useState('');
  const [gust, setGust] = useState('');
      
  var apiKey = "8f203b16150b3debb67a311e1a97d4bf";
  var lang = "en";
  var units = "metric";
  var url = `https://api.openweathermap.org/data/2.5/weather?q=${location}&units=${units}&appid=${apiKey}&lang=${lang}&`;

  const searchLocation = (event) => {
    if(event.key === "Enter"){
      axios.get(url)
        .then((response) => {
          console.clear();
          setData(response.data)
          console.log(response.data)
          setWeather(response.data.weather)
          setTemp(response.data.main.temp)
          setFeelsLikeTemp(response.data.main.feels_like)
          setGust(response.data.wind.gust)
          setErrorMessage("")
        }).catch(err => {
          console.log(err)
          setErrorMessage("Please enter another location")
          setData({})
          setWeather('')
          
        })
        setLocation('');
    }
  }
  return (
    <>
      <Head>
        <title>Weather App</title>
        <meta name="  description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <InputBox location={location} searchLocation={searchLocation} setLocation={setLocation}/>
        {
          weather && weather.map((w, index) =>   {
            return(
                <WeatherInfo data={data} w={w} index={index} temp={temp} feelsLikeTemp={feelsLikeTemp} gust={gust} />
            )
          })
        }
        <ErrorInfo errorMessage={errorMessage}/>
      </main>
    </>
  )
}
